### ISSUE TITLE
Smaller Docker container

### ISSUE THREAD

**Issue by adamlc** [AcalephStorage/consul-alerts#121]
Just wanted to say thanks for this great app, we're using it in production.

I just wondered if its would make sense to reduce the size of the container? I've noticed its over 800mb which seems a little excessive considering go apps can be statically compiled. Might it be worth looking at something like [golang-builder](https://github.com/CenturyLinkLabs/golang-builder) which builds a tiny container without all the bloat of the golang container.

😄

**Comment by fusiondog** [comment]
Hey, 
Just update the docker container using alpine as the base.  Current image with both consul and consul-alerts is 46MB.  golang-builder looks cool though.  I'll keep that in mind for the future.
