### ISSUE TITLE
Disable notifications for warnings only

### ISSUE THREAD

**Issue by adamlc** [AcalephStorage/consul-alerts#122]
We have [Vault](https://www.vaultproject.io/) registered in consul. Vault will return a 429 status for nodes that are in standby, so this displays as a warning in consul, but in this instance the warning is perfectly valid because the nodes are healthy but in standby, so it would be nice to disable warnings only for a service, rather than all notifications 😄

**Comment by msupino** [comment]
How do u check vault to get status 429?

**Comment by adamlc** [comment]
This behaviour has actually changed now, so this is no longer relevant :)
