### ISSUE TITLE
consul-alerts does not alert :(

### ISSUE THREAD

**Issue by nfoonf** [AcalephStorage/consul-alerts#136]
Hi,

I have some serious issues getting consul-alerts to work. 
My setup consists of a consul inside a docker swarm all deployed by docker-compose:

    volumes:
    consul-data: {}
    alert-logs: {}
    services:
    consul-server:
        extends:
            service: consul-server
            file: ../consul/consulbase.yml
        command: agent -server -bootstrap -dc foo-project -node consul1 -ui --advertise ${CONSUL_MASTER_IP} -data-dir /consul-data/consul -domain xip.io
    consul-alerts:
        extends:
            service: consul-alerts
            file: ../consul/consulbase.yml
        command: start --consul-addr=127.0.0.1:8500 --log-level=debug --consul-dc=foo-project

consul alerts seems to startup normally and everything seems fine.

I now deploy a service, and try to configure consul-alerts to check on this service and alert me if necessary:

    docker run -p 0.0.0.0:80:80 -p 0.0.0.0:443:443 -e "SERVICE_ID=nginx" -d nginx

    # {
    #        "id": "nginx",
    #        "name": "nginx status",
    #        "http": "http://localhost:80",
    #        "service_id": "nginx",
    #        "interval": "10s",
    #        "timeout": "1s"
    # }

    # register check
    curl -vv -H "Content-Type: application/json" -X POST localhost:8500/v1/agent/check/register -d @nginx-check.json
    
    # configure email notifier
    curl -vv -X PUT localhost:8500/v1/kv/consul-alerts/config/notifiers/log/enabled -d 'true'
    curl -vv -X PUT localhost:8500/v1/kv/consul-alerts/config/notifiers/email/enabled -d 'true'
    curl -vv -X PUT localhost:8500/v1/kv/consul-alerts/config/notifiers/email/url -d 'mail.xxxx.de'
    curl -vv -X PUT localhost:8500/v1/kv/consul-alerts/config/notifiers/email/port -d '25'
    curl -vv -X PUT localhost:8500/v1/kv/consul-alerts/config/notifiers/email/username -d 'xxxx'
    curl -vv -X PUT localhost:8500/v1/kv/consul-alerts/config/notifiers/email/password -d 'xxxx'
    curl -vv -X PUT localhost:8500/v1/kv/consul-alerts/config/notifiers/email/receivers -d '["groening@silpion.de"]'
    
    # configure notifier profile
    curl -vv -X PUT localhost:8500/v1/kv/consul-alerts/config/notif-profiles/log_mail -d '{ "Interval": 10, "NotifList": { "log":true, "email":true }'
    
    # configure notif-profile
    curl -vv -X PUT localhost:8500/v1/kv/consul-alerts/config/notif-profiles/default -d '{ "Interval": 10, "NotifList": { "log":true, "email":true }'
    
    # enable check
    curl -vv -X PUT localhost:8500/v1/kv/consul-alerts/config/checks/enabled/nginx -d 'true'
    curl -vv -X PUT localhost:8500/v1/kv/consul-alerts/consul-alerts/config/notifiers/log/path -d '/logs/consul.log'
    
    #
    curl -vv -X PUT localhost:8500/v1/kv/consul-alerts/config/notif-selection/services/nginx -d 'log_mail'

I think I followed your docs as good as I could. Am I missing something?

**Comment by fusiondog** [comment]
Is anything showing in the debug data?  It may be possible it is something to do with docker networking and it isn't connecting to the consul instance properly.

**Comment by nfoonf** [comment]
No this works properly, consul-alerts connects to the cluster properly, even wins the leader election:

    time="2016-08-10T07:51:01Z" level=info msg="Checking consul agent connection..." 
    time="2016-08-10T07:51:01Z" level=info msg="Registering new health check: node=consul1, service=, check=Serf Health Status, status=passing" 
    time="2016-08-10T07:51:01Z" level=info msg="Consul ACL Token: \"\"" 
    time="2016-08-10T07:51:01Z" level=info msg="Consul Alerts daemon started" 
    time="2016-08-10T07:51:01Z" level=info msg="Consul Alerts Host: localhost.localdomain" 
    time="2016-08-10T07:51:01Z" level=info msg="Consul Agent: 127.0.0.1:8500" 
    time="2016-08-10T07:51:01Z" level=info msg="Consul Datacenter: XXXX" 
    time="2016-08-10T07:51:01Z" level=info msg="Started Consul-Alerts API" 
    time="2016-08-10T07:51:01Z" level=info msg="Running for leader election..." 
    time="2016-08-10T07:51:01Z" level=info msg="Now acting as leader." 

Consul also seems good so far:

    ==> WARNING: Bootstrap mode enabled! Do not enable unless necessary
    ==> Starting Consul agent...
    ==> Starting Consul agent RPC...
    ==> Consul agent running!
             Node name: 'consul1'
            Datacenter: 'tXXX'
                Server: true (bootstrap: true)
           Client Addr: 127.0.0.1 (HTTP: 8500, HTTPS: -1, DNS: 8600, RPC: 8400)
          Cluster Addr: 127.0.0.1 (LAN: 8301, WAN: 8302)
        Gossip encrypt: false, RPC-TLS: false, TLS-Incoming: false
                 Atlas: <disabled>

    ==> Log data will now stream in as it occurs:

        2016/08/10 07:50:51 [INFO] raft: Node at 127.0.0.1:8300 [Follower] entering Follower state
        2016/08/10 07:50:51 [INFO] serf: EventMemberJoin: consul1 127.0.0.1
        2016/08/10 07:50:51 [INFO] consul: adding LAN server consul1 (Addr: 127.0.0.1:8300) (DC: XXX)
        2016/08/10 07:50:51 [INFO] serf: EventMemberJoin: consul1.XXX 127.0.0.1
        2016/08/10 07:50:51 [INFO] consul: adding WAN server consul1.XXX (Addr: 127.0.0.1:8300) (DC: XXX)
        2016/08/10 07:50:51 [ERR] agent: failed to sync remote state: No cluster leader
        2016/08/10 07:50:51 [ERR] agent: failed to sync changes: No cluster leader
        2016/08/10 07:50:51 [ERR] agent: failed to sync changes: No cluster leader
        2016/08/10 07:50:51 [ERR] agent: failed to sync changes: No cluster leader
        2016/08/10 07:50:51 [ERR] agent: failed to sync changes: No cluster leader
        2016/08/10 07:50:51 [ERR] agent: failed to sync changes: No cluster leader
        2016/08/10 07:50:51 [ERR] agent: failed to sync changes: No cluster leader
        2016/08/10 07:50:51 [ERR] agent: failed to sync changes: No cluster leader
        2016/08/10 07:50:51 [ERR] agent: failed to sync changes: No cluster leader
        2016/08/10 07:50:51 [ERR] agent: failed to sync changes: No cluster leader
        2016/08/10 07:50:52 [WARN] raft: Heartbeat timeout reached, starting election
        2016/08/10 07:50:52 [INFO] raft: Node at 127.0.0.1:8300 [Candidate] entering Candidate state
        2016/08/10 07:50:52 [INFO] raft: Election won. Tally: 1
        2016/08/10 07:50:52 [INFO] raft: Node at 127.0.0.1:8300 [Leader] entering Leader state
        2016/08/10 07:50:52 [INFO] consul: cluster leadership acquired
        2016/08/10 07:50:52 [INFO] consul: New leader elected: consul1
        2016/08/10 07:50:52 [INFO] raft: Disabling EnableSingleNode (bootstrap)
        2016/08/10 07:50:52 [INFO] consul: member 'consul1' joined, marking health alive
        2016/08/10 07:50:53 [INFO] agent: Synced service 'localhost.localdomain:consul-server:8302'
        2016/08/10 07:50:53 [INFO] agent: Synced service 'localhost.localdomain:consul-server:8302:udp'
        2016/08/10 07:50:53 [INFO] agent: Synced service 'localhost.localdomain:consul-server:8600:udp'
        2016/08/10 07:50:53 [INFO] agent: Synced service 'localhost.localdomain:consul-server:8300'
        2016/08/10 07:50:53 [INFO] agent: Synced service 'consul'
        2016/08/10 07:50:53 [INFO] agent: Synced service 'localhost.localdomain:consul-server:8301:udp'
        2016/08/10 07:50:53 [INFO] agent: Synced service 'localhost.localdomain:consul-server:8400'
        2016/08/10 07:50:53 [INFO] agent: Synced service 'localhost.localdomain:consul-server:8500'
        2016/08/10 07:50:53 [INFO] agent: Synced service 'localhost.localdomain:consul-alerts:9000'
        2016/08/10 07:50:53 [INFO] agent: Synced service 'localhost.localdomain:consul-server:8301'

**Comment by fusiondog** [comment]
That looks fine.  The check shows in the consul ui?  Does anything show in the consul-alerts log show when the nginx service is stopped to trigger alert or it shows nothing?

**Comment by gnur** [comment]
In my experience, without the `--watch-checks` flag consul-alerts won't send any alerts.

**Comment by ankurgla22** [comment]
Same issue. Do any one knows it's solution?

**Comment by fusiondog** [comment]
@gnur has hit the point here.  It is really just a documentation bug.  The --watch-checks is required to actually Watch Checks.  The docker related info in the Readme doesn't list it.  I will update that now.

**Comment by ankurgla22** [comment]
@fusiondog Yes, that's  right.
It works. thanks
