### ISSUE TITLE
Discussion: HA

### ISSUE THREAD

**Issue by dpetzel** [AcalephStorage/consul-alerts#16]
So we were talking internally today about how best to ensure the alerts service is "always up". There are clearly lots of ways to do this, but here is what we came up with and I'm interested if a similar approach makes sense to be supported by the service itself.

__Goals__
* We don't want a dead instance/node to result in us losing alerting for any duration of time. A few seconds or a minute is OK
* We'd like to avoid the traditional (AKA complicated) HA solutions involving thinks like pacemaker and friends
* We don't want multiple alerts fired for a single state change. IE if we have 5 consul servers and a service goes into error, we only want one email.

__Current Direction__
We want to install the alerts daemon on every consul **server**. We are then going to drop a small cron script that is going to check if the current node is the leader or not. In all cases the daemon will continue to run, however if the node is not the current leader we are going to disable the watch. So effectively we'll have 4 "warm standbys" and should the leader fail, we'll let Consul do its thing around re-election and picky back on that.

We are using [Chef to manage the daemon] (https://github.com/dpetzel/consul_alerts-cookbook), but we don't converge Chef frequently enough for this to be effective. Similar logic would exist in the Chef recipe so Chef wasn't fighting with the cron script. 

__Awesomeness__
If there were some sort of `leader_mode` flag that could be passed to `consul-alerts` at startup this would be perfect for our use case. The daemon would continue to run, and the watch would stay in place on all the servers, however when Consul alerts sees its running on the same node as the master, it would process alerts, if its not running on the master it would simply be a noop.

I'm totally open to any other idea folks might have on how best to pull of the goals.

Thanks

**Comment by darkcrux** [comment]
Leader elections is now in place and is done automatically. Only the leader will send out notifications. Only works for checks and not events though as we may still want to trigger events on specific nodes.

**Comment by lyrixx** [comment]
@darkcrux Thanks for this feature ;)

Could you release a new version? thanks.

**Comment by sean-** [comment]
A new version has been released... can we close this issue?
