### ISSUE TITLE
Unable to send mail using GMail SMTP; TLS issue?

### ISSUE THREAD

**Issue by rvalyi** [AcalephStorage/consul-alerts#19]
Hello

first thanks for this great tool!
It seems I managed to set up everything and in the logs I could observe checks notifications happening. But when I tried to use mail notifier with GMail SMTP, I receive no email and i the log I typically receive:

```
INFO[0086] Processing health checks for notification.   
INFO[0213] Unable to send notification: dial tcp 64.233.171.108:587: connection timed out
```

(64.233.171.108 is the IP of smtp.gmail.com)

Sorry, I know very little about Golang to debug...
But I think it may be because GMail SMTP forces you to use TLS.
Here is an example how they do it in Python for instance http://segfault.in/2010/12/sending-gmail-from-python/

Specially see session.starttls() before login and sendmail

So may be we should us too use StartTLS() in your email-notifier before auth here
https://github.com/AcalephStorage/consul-alerts/blob/master/notifier/email-notifier.go#L86 ?

Again, this is pure extrapolation, but may be we could have a KV to force TLS and if this option is true, then you call StartTLS()

I'm sorry in fact I was unable to build the image because of lack of Golang knowledge. Eventually would be cool if you could have a section explaining how to build the project (I'm using Ubuntu), I typically have this error when doing go install:

```
root@cloudmaster:~/golang/src/github.com/AcalephStorage/consul-alerts# go install                                                                                      
check-handler.go:14:2: cannot find package "github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/Sirupsen/logrus" in any of:
        /root/.gvm/gos/go1.3.3/src/pkg/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/Sirupsen/logrus (from $GOROOT)
        /root/src/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/Sirupsen/logrus (from $GOPATH)
consul-alerts.go:17:2: cannot find package "github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/docopt/docopt-go" in any of:
        /root/.gvm/gos/go1.3.3/src/pkg/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/docopt/docopt-go (from $GOROOT)
        /root/src/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/docopt/docopt-go (from $GOPATH)
check-handler.go:11:2: cannot find package "github.com/AcalephStorage/consul-alerts/consul" in any of:
        /root/.gvm/gos/go1.3.3/src/pkg/github.com/AcalephStorage/consul-alerts/consul (from $GOROOT)
        /root/src/github.com/AcalephStorage/consul-alerts/consul (from $GOPATH)
check-handler.go:12:2: cannot find package "github.com/AcalephStorage/consul-alerts/notifier" in any of:
        /root/.gvm/gos/go1.3.3/src/pkg/github.com/AcalephStorage/consul-alerts/notifier (from $GOROOT)
        /root/src/github.com/AcalephStorage/consul-alerts/notifier (from $GOPATH)
```

If you help me build I could test the TLS thing for you...

**Comment by aardestani** [comment]
I have a certificate related problem with sending mails through mailgun, looks like it does not work with wildcard certificates as below

Unable to send notification: x509: certificate is valid for *.mailgun.org, mailgun.org, not smtp.mailgun.com

I am trying Consul Alerts 0.3.0 with windows 2012 R2 Standard.
