### ISSUE TITLE
Build failure on docker hub

### ISSUE THREAD

**Issue by fpalladoro** [AcalephStorage/consul-alerts#197]
Hi guys, the automatic docker build failed this past weekend with the following error: 
```
Build failed: The command '/bin/sh -c mkdir -p /go && apk update && apk add bash ca-certificates git go alpine-sdk && go get -v github.com/AcalephStorage/consul-alerts && mv /go/bin/consul-alerts /bin && go get -v github.com/hashicorp/consul && mv /go/bin/consul /bin && rm -rf /go && apk del --purge go git alpine-sdk && rm -rf /var/cache/apk/*' returned a non-zero code: 1
```

The last merge on master was https://github.com/AcalephStorage/consul-alerts/pull/195 but I can't find any issues with that. I can build the docker image perfectly in my environment. Could it been a glitch in docker hub build? Is it possible to retry the build?

**Comment by Gerrrr** [comment]
Hey @fpalladoro 

Unfortunately, I don't have permissions to retry the build. Maybe @fusiondog can help?

**Comment by fpalladoro** [comment]
New automatic builds ran successfully since a couple a PRs were merged. I'm marking this issue as closed
