### ISSUE TITLE
Custom configuration by CLI

### ISSUE THREAD

**Issue by hunter** [AcalephStorage/consul-alerts#2]
Add support for loading a default custom configuration via command/api instead of manually editing consul's KV

**Comment by justicel** [comment]
Any update on getting this implemented. I just built a puppet module for this project: https://forge.puppetlabs.com/jlondon/consul_alerts
Having a static config file option would make life much easier :)

**Comment by fusiondog** [comment]
At the moment my intent is to use chef to configure this and make use of consul_kv cookbook to set keys in consul-alerts.  I plan to look into making consul-ui aware of consul-alerts and add checkboxes and such to set blacklist and profile selection.

**Comment by fusiondog** [comment]
The docs now describe using consulate to load a json custom config file.
