### ISSUE TITLE
Feature request: add alerts for Nomad

### ISSUE THREAD

**Issue by mnuic** [AcalephStorage/consul-alerts#224]
Hi, 

It would be good to have alerts for Nomad cluster, eg. monitor jobs, tasks, allocation, draining, OOM, job restarts, service migration to another host, etc. 

Thanks

**Comment by Gerrrr** [comment]
Hi @mnuic ,

We also use Nomad for scheduling the jobs and it would indeed be nice to reuse Consul-Alters for the cluster notifications. Unfortunately, Nomad (we are still on `v0.5.4`, haven't checked newer versions) does not share this information with Consul.

**Comment by mnuic** [comment]
Nomad and Consul are closely coupled (hashicorp) and I don't see that there would be any problems integrating this in consul-alerts. I mean, Nomad has it's own [api](https://github.com/hashicorp/nomad/tree/master/api) and consul-alerts should have to know to work with that.

The last stable version of Nomad is 0.7.1.

**Comment by shivmishra88** [comment]
Consul-alert is watching services registered in consul (consul version 0.9.3). When we have all nomad (version v0.7.1) jobs also registered in consul, consul-alert is not checking the services coming from nomad. 
Consul-alert is only working for services which we manually register by creating JSON files.

**Comment by shivmishra88** [comment]
We found that when we have service tags in nomad jobs, the key value doesn't get created in CONSUL-ALERTS/CHECKS/ for that job.
