### ISSUE TITLE
bug: panic invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mnuic** [AcalephStorage/consul-alerts#229]
```
A.B.C.D panic: runtime error: invalid memory address or nil pointer dereference
 A.B.C.D [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x55ce325fa040]
 A.B.C.D
 A.B.C.D goroutine 23 [running]:
 A.B.C.D github.com/AcalephStorage/consul-alerts/consul.(*ConsulAlertClient).updateHealthCheck(0xc42024e000, 0xc420552230, 0x62, 0xc42029aa00)
 A.B.C.D 	/go/src/github.com/AcalephStorage/consul-alerts/consul/client.go:565 +0x80
 A.B.C.D github.com/AcalephStorage/consul-alerts/consul.(*ConsulAlertClient).UpdateCheckData(0xc42024e000)
 A.B.C.D 	/go/src/github.com/AcalephStorage/consul-alerts/consul/client.go:341 +0x6f5
 A.B.C.D main.(*CheckProcessor).handleChecks(0xc4202293b0, 0xc420652800, 0x78, 0x8d)
 A.B.C.D 	/go/src/github.com/AcalephStorage/consul-alerts/check-handler.go:111 +0x180
 A.B.C.D main.(*CheckProcessor).start(0xc4202293b0)
 A.B.C.D 	/go/src/github.com/AcalephStorage/consul-alerts/check-handler.go:28 +0x159
 A.B.C.D created by main.startCheckProcessor
 A.B.C.D 	/go/src/github.com/AcalephStorage/consul-alerts/check-handler.go:168 +0xfb
```

**Comment by Gerrrr** [comment]
Hello @mnuic,

Thanks for the bug report! Can you please provide more details? E.g. Consul-alerts version, Consul version, OS version, reproduction steps?

Best,
Aleks

**Comment by mnuic** [comment]
Hello @Gerrrr,

Consul alerts docker:
```
# /bin/consul-alerts --version
Consul Alerts 0.5.0
```

Consul version: 
```
consul:1.0.2
```

We have docker hosts on Ubuntu 16.04.04LTS, docker 17.12.1-ce

It happens sporadic. First time we noticed it consul-alerts service hasn't been restarted for some time, after that updated to last version 0.5.0. It was ok for a few days, and then started to show again. Don't know how to reproduce it, but sometimes it happens when we update/restart one of consul servers (we have 3 in dc).

**Comment by Gerrrr** [comment]
Thanks! Looks like it might happen when Consul does not have a leader.

I'll try to reproduce and fix it in the next couple of weeks.

**Comment by mnuic** [comment]
With newet versions of consu - 1.4.3, this panic happens all the time:
`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x560a020e202c]
/go/src/github.com/AcalephStorage/consul-alerts/consul/client.go:345 +0x6f3
goroutine 58 [running]:
main.(*CheckProcessor).start(0xc0003361e0)
main.(*CheckProcessor).handleChecks(0xc0003361e0, 0xc00060aa80, 0x91, 0xd3)
/go/src/github.com/AcalephStorage/consul-alerts/check-handler.go:168 +0xdd
github.com/AcalephStorage/consul-alerts/consul.(*ConsulAlertClient).updateHealthCheck(0xc00023adb0, 0xc002a42000, 0x3f, 0xc0007c1300)
/go/src/github.com/AcalephStorage/consul-alerts/consul/client.go:569 +0x8c
/go/src/github.com/AcalephStorage/consul-alerts/check-handler.go:28 +0x113
/go/src/github.com/AcalephStorage/consul-alerts/check-handler.go:111 +0x169
github.com/AcalephStorage/consul-alerts/consul.(*ConsulAlertClient).UpdateCheckData(0xc00023adb0)
created by main.startCheckProcessor
2019/04/13 23:01:28 [ERR] consul.watch: Watch (type: checks) errored: Unexpected response code: 500 (rpc error making call: EOF), retry in 5s`


Memory is above 200MB all the time.

And can we expect a new release soon with fix for this? 

Thanks
