### ISSUE TITLE
Update Pagerduty Notifications for API v2

### ISSUE THREAD

**Issue by ofavre** [AcalephStorage/consul-alerts#231]
PagerDuty API v1 is being [decommissioned](https://v2.developer.pagerduty.com/docs/v1-rest-api-decommissioning-faq) and will no longer work after 2018/10/19.

I opened darkcrux/gopherduty#2 to solve this, but that library has not been updated since 2015/01 so it's probably a dead end.

Using the official [PagerDuty/go-pagerduty](https://github.com/PagerDuty/go-pagerduty) library is probably better.

**Comment by joebowbeer** [comment]
@ofavre Can this issue be closed?

Your issue https://github.com/darkcrux/gopherduty/issues/2 was closed because gopherduty is only using the Events API, which is unaffected by the deprecation of PagerDuty v1 REST API.

**Comment by ofavre** [comment]
Yes we can.
