### ISSUE TITLE
Some thoughts about consul-alerts

### ISSUE THREAD

**Issue by lyrixx** [AcalephStorage/consul-alerts#26]
We are using consul-alerts for few weeks now, and I want to share my thoughts.

I like it, but I thinks there is room for improvement.

I Like the system of notification. It's simple and efficient. We planned to build an full HTML+JS application to managed it. But there is no ETA about it. So if someone already started / finished it, it would be awesome.

I like  the black list feature

I like the retention system to avoid flapping. But I think it could be more fine-tunable. Because we are running some checks every 5 minutes (like zip integrity). So it does not work well with consul-alerts retention.

I don't like the notification messages. We have about 40 nodes, and on each node from 3 to 30 checks. And now, it's really hard to have a good overview of the macro and micro state of the cluster.
For example, In my mail box, I have theses email subject sorted by **date**

```
SensioLabs is HEALTHY
SensioLabs is HEALTHY
SensioLabs is UNSTABLE
SensioLabs is HEALTHY
SensioLabs is UNSTABLE
SensioLabs is UNSTABLE
SensioLabs is HEALTHY
SensioLabs is HEALTHY
```

So I have to open each mail to know which node is OK or KO. Then, I have to remember all KO checks because when I get a new mail, consul-alerts list only changed state nodes.

So I propose something like:
- in each mails / notification, list all checks in a warning or critical node
- in each mails / notification, list all checks in a healthy state in comparison with the previous mail  / notification

To not break the BC, we could use a flag to enable  / disable this feature.

**Comment by badmadrad** [comment]
+1 I have to second this. First, I have been using consul-alerts for about 2 hours and its amazing work so far. That being said, I do think the subject line in the email could at least possibly highlight the node name and check.

**Comment by WangFenjin** [comment]
Hi @lyrixx  , not sure if you had time to build a website to show the alert?

Thanks.

**Comment by lyrixx** [comment]
Not really. Sorry.

**Comment by arj22** [comment]
+1 for mar-io's suggestion. A Nagios-like subject would be great. 
Host - Check Name - Check Status

**Comment by lyrixx** [comment]
I don't use this tool anymore. I'm closing this issue since it's not relevant anymore.
thanks for your work
