### ISSUE TITLE
Support JWT auth for HTTP notifier

### ISSUE THREAD

**Issue by onimsha** [AcalephStorage/consul-alerts#271]
Currently http notifier does not support Token authentication using JWT, i'd like to add support to it as following:

config prefix: `consul-alerts/config/notifiers/http-endpoint/`

Key | Type | Description
token | base64-encoded | Token to set on the 'Authorization' header

| Key        | Type           | Description  |
| ------------- |:-------------:| -----:|
| token      | base64-encoded  | Token to set on the 'Authorization' header |

When sending payload, http notifier will use the token and create the header as following 'Authorization: Bearer $token' .

**Comment by fusiondog** [comment]
I assume that a separate process would be required to set the token and consul-alerts would just be in charge of presenting whatever would be found there.

**Comment by onimsha** [comment]
Yes, since the notifier config is using consul KV, we can sett the token in the config prefix.
