### ISSUE TITLE
Node blacklist does not work as expected

### ISSUE THREAD

**Issue by lyrixx** [AcalephStorage/consul-alerts#28]
* During our deploy, I blacklist all nodes.  And after the deploy, I un-blacklist the nodes.
* I have severals services that have checks with TTL.
* During the deploy, theses services are down

And so, when I re-enable the monitoring, I get N notifications like that:

> insight-d1.consumer-0:insight.analysis_feedback:Service 'insight.analysis_feedback' check is passing.
insight-d1.consumer-0:insight.analysis_feedback:Service 'insight.analysis_feedback' check is passing.
insight-d1.consumer-0:insight.analysis_feedback_collector:Service 'insight.analysis_feedback_collector' check is passing.
insight-d1.consumer-0:insight.analysis_kill:Service 'insight.analysis_kill' check is passing.
insight-d1.consumer-0:insight.analysis_new:Service 'insight.analysis_new' check is passing.
insight-d1.consumer-0:insight.comment_add:Service 'insight.comment_add' check is passing.
insight-d1.consumer-0:insight.mail:Service 'insight.mail' check is passing.
insight-d1.consumer-0:insight.notification:Service 'insight.notification' check is passing.
insight-d1.consumer-0:insight.scm_hook:Service 'insight.scm_hook' check is passing.

I should not, because theses nodes were down only during the deploy. More over, I never get the "service are down" notification.

**Comment by darkcrux** [comment]
This was fixed last month. Whoops forgot to close the issue. Will push out a new build soon.
