### ISSUE TITLE
If starting consul-alert when Consul is starting, consul-alerts seemingly get stuck without exiting *or* alerting

### ISSUE THREAD

**Issue by vidarh** [AcalephStorage/consul-alerts#33]
This happened when starting consul-alerts (in Docker container built with "go get ..." based on the "golang" container) before Consul was fully initialized on the host:

    root@1dab0b580258:/go/bin# /go/bin/consul-alerts start --alert-addr=0.0.0.0:9000 --consul-addr=192.168.0.44:8500
    INFO[0000] Checking consul agent connection...
    INFO[0000] Unable to load custom config, using default instead: Unexpected response code: 500
    INFO[0000] Consul Alerts daemon started
    INFO[0000] Consul Alerts Host: 1dab0b580258
    INFO[0000] Consul Agent: 192.168.0.44:8500
    INFO[0000] Consul Datacenter: dc1 
    WARN[0000] Unable to retrieve list of sessions.
    ERRO[0000] Unable to create new sessions: Unexpected response code: 500 (No cluster leader)
    ERRO[0000] Failed to run Consul KV Acquire: Unexpected response code: 500 (No cluster leader)

At this point it hung until I ctrl-c'd it. On restart, it then started fine.

**Comment by vidarh** [comment]
My fault. This is because I left out "--watch-checks".. Though it seems my (older) binary in the docker container runs the checks regardless? 

This still seems like broken behaviour, though, if the checks are not processed without extra config options if the Consul config settings indicates they're enabled, but I'll close since what is described is not actually a bug.

**Comment by fizerkhan** [comment]
I had this issue. Following code work for me.

```
consul-alerts start --alert-addr=0.0.0.0:9000 --consul-addr=localhost:8500 --consul-dc=default --watch-checks
```

**Comment by ramilbermejo** [comment]
Hello! 


I just wanted to show  you my new web page  layout,  take  a  look here  <http://cause.nisarsayed.com/e3ryx>

My best to you, r.bermejo1983
