### ISSUE TITLE
Leader election can hang

### ISSUE THREAD

**Issue by vidarh** [AcalephStorage/consul-alerts#40]
Unfortunately I have not been able to reproduce this yet, but I have a three node Consul cluster where I am running one instance of Consul-alerts on the same server as each Consul node, where the cluster got into a state where the node whose host name was in consul-alert/leader key believed it was not the leader. 

Restarting consul-alerts on the node in question did not appear to resolve the issue, but restarting the consul node did, so I'm not sure if this is a consul-alerts issue or a consul issue or something else.

A couple of observations regardless where the problem is:

Some mechanism is needed to verify that the leader is still live, and not just sufficiently undead to hold on to the lock. 

One approach is to force leadership elections every N minutes, and to make the other nodes alert if the current leader does not relinquish the lock as part of that. Another alternative is for the other nodes to register health checks against the alert endpoint of the leader, and alert if those health checks fail, even when they're not the leader.

An alternative might be for the cluster leader to provide a heartbeat by regularly updating an un-locked key, and for the other members to verify that the key has been recently updated and otherwise alert.

**Comment by darkcrux** [comment]
I've merged a PR that fixes this issue. Will also try and see if consul's native leader election might be a better solution to this. If not, find a better way to do this. I kinda like the heartbeat idea.

**Comment by vidarh** [comment]
Great. FWIW I've not seen this problem re-occur despite running 3x instances of consul-alert in each of four separate test/dev environments, so it seems to be pretty rare in the first place.

**Comment by darkcrux** [comment]
Closing this now. :)
