### ISSUE TITLE
Alerts on Warning status as well as Critical status

### ISSUE THREAD

**Issue by rudijs** [AcalephStorage/consul-alerts#42]
Hi,
I'm using the email notification and so far am only able to get message about Critical statuses.

Is there an option for Warning status notifications as well?

I might have overlooked where to set that option, any tips much appreciated.

Thank you.

**Comment by lyrixx** [comment]
I use consul alerts too and I get emails about warning

**Comment by rudijs** [comment]
@lyrixx I see, interesting. I'll have to dig more into it my end.

Thanks.

**Comment by rudijs** [comment]
Misconfiguration on my end, works all good, sorry my bad.

Thanks.
