### ISSUE TITLE
Released file is different from the document

### ISSUE THREAD

**Issue by kenjiskywalker** [AcalephStorage/consul-alerts#43]
Hi!

This tool is very cool :+1: 
I want to use Slack notification.

So but, Document and  `v0.2.0` option is different.
Please update archive file. :bow:

**Comment by darkcrux** [comment]
Hi @kenjiskywalker 

we just release v0.3.0 which should match the options in the Doc. Also updated the README with a link to the latest binaries which gets built every time new changes are pushed.

**Comment by kenjiskywalker** [comment]
@darkcrux 

Thaks :smile:
