### ISSUE TITLE
Consul-alert panics

### ISSUE THREAD

**Issue by lyrixx** [AcalephStorage/consul-alerts#45]
```
time="2015-02-20T13:58:42Z" level=warning msg="Unable to retrieve node name."
panic: interface conversion: interface is nil, not string

goroutine 13 [running]:
github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper.(*Candidate).retrieveNode(0xc20800d900)
        /usr/local/go/src/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper/skipper.go:141 +0x257
github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper.(*Candidate).campaign(0xc20800d900)
        /usr/local/go/src/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper/skipper.go:99 +0x36
github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper.(*Candidate).campaign(0xc20800d900)
        /usr/local/go/src/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper/skipper.go:131 +0x994
github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper.(*Candidate).campaign(0xc20800d900)
        /usr/local/go/src/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper/skipper.go:131 +0x994
created by github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper.(*Candidate).RunForElection
        /usr/local/go/src/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper/skipper.go:46 +0x32

goroutine 1 [chan receive]:
main.daemonMode(0xc2080abc80)
        /home/ubuntu/.buildbox/Agent/acaleph/consul-alerts/consul-alerts.go:110 +0x111e
main.main()
        /home/ubuntu/.buildbox/Agent/acaleph/consul-alerts/consul-alerts.go:49 +0x13c

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init�1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x35
goroutine 48 [select]:
net/http.(*persistConn).writeLoop(0xc208064580)
        /usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:661 +0xcbc

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 47 [IO wait]:
net.(*pollDesc).Wait(0xc2080b2fb0, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080b2fb0, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2080b2f50, 0xc208076000, 0x1000, 0x1000, 0x0, 0x7f0d378f6d30, 0xc2080b1ba8)
        /usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc2080360c8, 0xc208076000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7f0d378f8460, 0xc2080360c8, 0xc2080645d8, 0xc208076000, 0x1000, 0x1000, 0x756ea0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc208080fc0, 0xc208076000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
        <autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc20814aa20)
        /usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc20814aa20, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc208064580)
        /usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 14 [syscall]:
syscall.Syscall6(0x3d, 0x3cfd, 0xc2080c4c14, 0x0, 0xc208063320, 0x0, 0x0, 0x7f0d378e5000, 0x40a0b1, 0xc20814a380)
        /usr/local/go/src/syscall/asm_linux_amd64.s:46 +0x5
syscall.wait4(0x3cfd, 0xc2080c4c14, 0x0, 0xc208063320, 0x90, 0x0, 0x0)
        /usr/local/go/src/syscall/zsyscall_linux_amd64.go:124 +0x79
syscall.Wait4(0x3cfd, 0xc2080c4c5c, 0x0, 0xc208063320, 0x0, 0x0, 0x0)
        /usr/local/go/src/syscall/syscall_linux.go:224 +0x60
os.(*Process).wait(0xc2081455c0, 0x0, 0x0, 0x0)
        /usr/local/go/src/os/exec_unix.go:22 +0x103
os.(*Process).Wait(0xc2081455c0, 0xc208065080, 0x0, 0x0)
        /usr/local/go/src/os/doc.go:45 +0x3a
os/exec.(*Cmd).Wait(0xc208066f00, 0x0, 0x0)
        /usr/local/go/src/os/exec/exec.go:364 +0x23c
os/exec.(*Cmd).Run(0xc208066f00, 0x0, 0x0)
        /usr/local/go/src/os/exec/exec.go:246 +0x71
main.runWatcher(0xc20800c53e, 0xe, 0xc20800c67d, 0x3, 0x822f30, 0x6)
        /home/ubuntu/.buildbox/Agent/acaleph/consul-alerts/watchers.go:26 +0x261
created by main.daemonMode
        /home/ubuntu/.buildbox/Agent/acaleph/consul-alerts/consul-alerts.go:93 +0xe20

goroutine 15 [chan receive]:
main.processEvents()
        /home/ubuntu/.buildbox/Agent/acaleph/consul-alerts/event-handler.go:42 +0x72
created by main.daemonMode
        /home/ubuntu/.buildbox/Agent/acaleph/consul-alerts/consul-alerts.go:99 +0xe8f

goroutine 16 [chan receive]:
main.processChecks()
        /home/ubuntu/.buildbox/Agent/acaleph/consul-alerts/check-handler.go:51 +0x47
created by main.daemonMode
        /home/ubuntu/.buildbox/Agent/acaleph/consul-alerts/consul-alerts.go:100 +0xea0

goroutine 18 [IO wait]:
net.(*pollDesc).Wait(0xc20814c6f0, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20814c6f0, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc20814c690, 0x0, 0x7f0d378f6d30, 0xc2081514c0)
        /usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc208036540, 0x48cede, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net/http.tcpKeepAliveListener.Accept(0xc208036540, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1976 +0x4c
net/http.(*Server).Serve(0xc20814a2a0, 0x7f0d378f8c68, 0xc208036540, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1728 +0x92
net/http.(*Server).ListenAndServe(0xc20814a2a0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1718 +0x154
net/http.ListenAndServe(0xc2080522ec, 0xe, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1808 +0xba
created by main.daemonMode
        /home/ubuntu/.buildbox/Agent/acaleph/consul-alerts/consul-alerts.go:106 +0xf76
```

**Comment by vidarh** [comment]
We now have this happening regularly on several servers. Here's a small excerpt:

Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: panic: interface conversion: interface is nil, not string
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: goroutine 12 [running]:
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper.(*Candidate).retrieveNode(0xc208100b90)
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: /go/src/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper/skipper.go:141 +0x257
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper.(*Candidate).campaign(0xc208100b90)
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: /go/src/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper/skipper.go:99 +0x36
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper.(*Candidate).campaign(0xc208100b90)
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: /go/src/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper/skipper.go:131 +0x994
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper.(*Candidate).campaign(0xc208100b90)
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: /go/src/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper/skipper.go:131 +0x994
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper.(*Candidate).campaign(0xc208100b90)
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: /go/src/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper/skipper.go:131 +0x994
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper.(*Candidate).campaign(0xc208100b90)
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: /go/src/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper/skipper.go:131 +0x994
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper.(*Candidate).campaign(0xc208100b90)
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: /go/src/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper/skipper.go:131 +0x994
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper.(*Candidate).campaign(0xc208100b90)
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: /go/src/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper/skipper.go:131 +0x994
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper.(*Candidate).campaign(0xc208100b90)
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: /go/src/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper/skipper.go:131 +0x994
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper.(*Candidate).campaign(0xc208100b90)
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: /go/src/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper/skipper.go:131 +0x994
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper.(*Candidate).campaign(0xc208100b90)
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: /go/src/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper/skipper.go:131 +0x994
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper.(*Candidate).campaign(0xc208100b90)
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: /go/src/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper/skipper.go:131 +0x994
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper.(*Candidate).campaign(0xc208100b90)
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: /go/src/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper/skipper.go:131 +0x994
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper.(*Candidate).campaign(0xc208100b90)
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: /go/src/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper/skipper.go:131 +0x994
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper.(*Candidate).campaign(0xc208100b90)
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: /go/src/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper/skipper.go:131 +0x994
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper.(*Candidate).campaign(0xc208100b90)
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: /go/src/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper/skipper.go:131 +0x994
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper.(*Candidate).campaign(0xc208100b90)
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: /go/src/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper/skipper.go:131 +0x994
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper.(*Candidate).campaign(0xc208100b90)
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: /go/src/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper/skipper.go:131 +0x994
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper.(*Candidate).campaign(0xc208100b90)
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: /go/src/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper/skipper.go:131 +0x994
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper.(*Candidate).campaign(0xc208100b90)
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: /go/src/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper/skipper.go:131 +0x994
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper.(*Candidate).campaign(0xc208100b90)
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: /go/src/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper/skipper.go:131 +0x994
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper.(*Candidate).campaign(0xc208100b90)
Sep 09 07:23:20 ip-172-31-46-100.ec2.internal docker[22626]: /go/src/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/darkcrux/consul-skipper/skipper.go:131 +0x994

**Comment by vidarh** [comment]
Ah, I see you've torn out consul-skipper, which presumably means you can close this as it's obsolete.

**Comment by darkcrux** [comment]
Closing this now. Thank.
