### ISSUE TITLE
No Alerts

### ISSUE THREAD

**Issue by outrunthewolf** [AcalephStorage/consul-alerts#50]
I haven't actually managed to get this to give me any alerts as yet.

I've entered in my email details, enabled it, and when my services go critical, I still get no email. Any idea what I might be doing wrong?

**Comment by darkcrux** [comment]
This might be just some configuration issues? Is there anything in the logs? Also, try other notifiers if they work. And check if the email details are correct.

**Comment by BCWilsonDotCom** [comment]
@outrunthewolf Are you running the watchers?

**Comment by outrunthewolf** [comment]
Unfortunately i'm not using this anymore. Closed.
