### ISSUE TITLE
No warning when alert-addr is already in use

### ISSUE THREAD

**Issue by liangshan** [AcalephStorage/consul-alerts#52]
I started consul-alert daemon with no error, but when I run the `consul watch consul-alert watch checks` it returned an error:

```
INFO[0005] consul-alert daemon is not running.
```

Then I searched the error in the source code, found that this error will occur when `http://consul-alert/v1/info` is not available.

Then i tried `telnet locahost 9000`, and could connect to that port, finally i found that PHP-FPM is taking that port, so the consul-alert daemon was not started completely.

So my question is, if the port is taken and can not bootstrap because of that, why no error or warning? Is that a bug or a special case with PHP-FPM?

**Comment by darkcrux** [comment]
Yeah I think a better error message would be better. Will update bootstraping to be more sensible.

**Comment by darkcrux** [comment]
error in binding to `alert-addr` now logs an error and exits.
