### ISSUE TITLE
Lock is not release when consul-alert crashes 

### ISSUE THREAD

**Issue by thedebugger** [AcalephStorage/consul-alerts#53]
We need to add health checks to the session so if the client stops or crashes, it releases the lock. I'll try submit a PR.

**Comment by thedebugger** [comment]
This issue is related to https://github.com/darkcrux/consul-skipper/issues/2

**Comment by euforia** [comment]
Is there  an update on this?  If not, I can try to implement the TTL mechanism as mentioned in  the above link.  Any thoughts, pointers or suggestions?

**Comment by darkcrux** [comment]
I think this is now fixed on the latest release. Switched from using consul-skipper to using the lock mechanism provided by the go consul-api library.

**Comment by euforia** [comment]
Awesome.. thanx.  I'm assuming off the master branch?

**Comment by darkcrux** [comment]
Yes. from the master branch. v0.3.2 also has this fixed. :)

**Comment by darkcrux** [comment]
I'm closing this now. Thanks.
