### ISSUE TITLE
No notification when consul leader down

### ISSUE THREAD

**Issue by nagumo5683** [AcalephStorage/consul-alerts#59]
I'm trying consul-alerts with 3 consul servers.
When a server node which is not a leader is down,  Serf Health Status faillure is notified.
But the leader node is down, no notification is occured.
Is it a bug?

**Comment by darkcrux** [comment]
Not entirely sure. Is consul still running at this point or is consul already in a leaderless state? consul-alerts still relies on consul being up and running with a leader.

**Comment by darkcrux** [comment]
Thinking about this more, when the consul leader is down, consul-alerts can't access consul for info on health statuses. When consul elects a new leader, consul-alerts should be able to capture the failing node by then.

**Comment by fusiondog** [comment]
Reading the original post it is unclear if the user was running redundant instances of consul-alerts with the 3 server consul cluster.  If the single consul-alerts instance was connected to the specific host that failed it would have stopped.  Closing pending update or more information.
