### ISSUE TITLE
Per-Service Threshold

### ISSUE THREAD

**Issue by DevBOFH** [AcalephStorage/consul-alerts#69]
Currently, it looks like the threshold level is a global setting for all services. Obviously this is a good idea for flapping services. However, I'd like to see it become far more granular. Not all services are equal and some services may flap quicker than others.

So maybe something like this in the KV store:

CONSUL-ALERTS/CONFIG/CHECKS/CHANGE-THRESHOLD/SERVICE/WARN.. PASS.. FAIL

Thoughts?

**Comment by darkcrux** [comment]
Sorry took a while to respond to this. I agree that not all services are equal. This could be a good addition. Will look into how this can be incorporated. Are you suggesting different thresholds for WARN/PASS/FAIL as well? Might make it more complicated.
