### ISSUE TITLE
hipchat integration, question

### ISSUE THREAD

**Issue by mverrall** [AcalephStorage/consul-alerts#70]
Hi, 

great idea so far, just wondering if you can confirm what the base-url should be I've tried a few combinations but none seem to be working so far :( 

Thanks,
Matt

**Comment by randyorr** [comment]
Hi. I am successfully using hipchat integration by leaving the base-url blank. The default base url is https://api.hipchat.com/v2/ and is set in https://github.com/AcalephStorage/consul-alerts/blob/master/Godeps/_workspace/src/github.com/tbruyelle/hipchat-go/hipchat/hipchat.go

**Comment by darkcrux** [comment]
I'll close this ticket now. Thanks.
