### ISSUE TITLE
Do not query too often consul, when consul reply with a 500

### ISSUE THREAD

**Issue by lyrixx** [AcalephStorage/consul-alerts#74]
Right now, If consul cluster has no elected leader yet, 
consul-alerts is going to try query consul **a lot**.

It not harmful, unless you collect log of consul. 
IMHO, there is not need for this intensive quering.
1 req / sec should be enough IMHO.

What do you think ?

**Comment by darkcrux** [comment]
Agree. This is strange though. As I was testing this with different scenarios, it never happened to me. Wonder if consul's version has anything to do with this. I'll look into it, I'll add a delay of 1 second on code and not just rely on the consul library. 

Thanks!

**Comment by scalp42** [comment]
@darkcrux I see this as well, it gets hammered.

**Comment by ch-acctg** [comment]
We are seeing this too, takes down consul, activates autoscaling, fun fun fun.

**Comment by darkcrux** [comment]
This should be fixed with #87.

**Comment by darkcrux** [comment]
Will put out a build soon.

**Comment by lyrixx** [comment]
I don't use this tool anymore. I'm closing this issue since it's not relevant anymore.
thanks for your work
