### ISSUE TITLE
Support influxdb 0.9

### ISSUE THREAD

**Issue by pcheliniy** [AcalephStorage/consul-alerts#77]
Good day.
Trying to configure the export of alerts into influxdb 0.9.2 and fails. Judging by the library in source code, it for version 0.8.  
Are there any plans on adding support of influxdb 0.9 ?

**Comment by BCWilsonDotCom** [comment]
+1

**Comment by darkcrux** [comment]
Would be good to add influxdb 0.9 support, also thinking if 0.8 should still be supported.

**Comment by hunter** [comment]
Influxdb 0.8 is not really supported any more. Perhaps the current version can be kept around for those with 0.8 and following releases only support 0.9?

**Comment by life1347** [comment]
hi, I just send a PR for adding support for influxdb 0.9. Hope it can help.

**Comment by adrianlop** [comment]
hi there, we're also interested in this. In fact, two days ago Influx stack was updated to v1.0
would be great to support this newer version too.

thanks! :smiley:

**Comment by fusiondog** [comment]
The existing PR pulls in the entire library for dependencies.  I think that a smaller subset of the tree could be set.  I haven't had time to fully review the options available there.  I'd be happy to see a new PR for v1.0 that resolved that question with a working godep tree that was more streamlined.

**Comment by imrangit** [comment]
We are also running v1.0 for influx and it is not working for that. I get this in logs:

time="2016-10-31T21:26:31Z" level=info msg="unable to send notifications:  Server returned (404): 404 page not found\n"

**Comment by Bullz3y3** [comment]
Also it would be good if UDP is supported. We are running influxdb 1.1

**Comment by eduponte** [comment]
Same here: v1.1

**Comment by nirmalthacker** [comment]
Same. Running influxdb v1.3 and hitting this error: "unable to send notifications: Server returned (404): 404 page not found\n"
