### ISSUE TITLE
Changing notifiers log path results in no log

### ISSUE THREAD

**Issue by ranpel** [AcalephStorage/consul-alerts#84]
Attempting to relocate the log by setting consul-alerts/config/notifiers/log/path to the desired file (fully qualified file name - /path/to/log.file) results in no output log at all.  Adjusting, bumping, wiggling and removing the keystore consul-alert keys did not repair the damage.

Notifications logging is g-gone.

starting command as so:
./consul-alerts start --consul-dc=ab-cd-ef
set key as so:
curl -X PUT -d "/opt/app/logging/notifications.log" http://localhost:8500/v1/kv/consul-alerts/config/notifiers/log/path
restart consul-alert agent
**wha? where? huh?**

and the running consul build is 0.5.2.  I gotta be missing something here.  Please let me know if you'd like more info.  Oh, this test case is on a single node consul agent running in bootstrap mode.

edit: after some back and forth it appears that wrapping my values for keys in double quotes for my curl commands does things.  Using single quotes has seemed to make everything as it should have been again.

**Comment by darkcrux** [comment]
that's a strange behaviour of curl, I'm closing this for now, might need to add better logging to detect this kind of issues though.
