### ISSUE TITLE
OpsGenie notifier creates a new alert when a check starts passing

### ISSUE THREAD

**Issue by EvanKrall** [AcalephStorage/consul-alerts#88]
When a check recovers when using the OpsGenie notifier, consul-alerts creates a new alert in OpsGenie with the content "server::check is passing", instead of closing the existing alert.

![screen shot 2015-12-12 at 12 58 06 pm](https://cloud.githubusercontent.com/assets/233961/11763858/0c5d5368-a0d0-11e5-9407-4df231600de6.png)

**Comment by dagvl** [comment]
I've created a pull request for this: #104

**Comment by fusiondog** [comment]
The pull request has been accepted.  Closing.
