### ISSUE TITLE
Running consul-alerts

### ISSUE THREAD

**Issue by akmalabbasov** [AcalephStorage/consul-alerts#92]
Is it enough to run consul-alerts daemon only on consul-server machines, or there should be a consul-alerts daemon in each machine which runs consul agent daemon?

**Comment by fusiondog** [comment]
You only need to run it on one machine for it to work.  If you have it on multiple machines it will fail over automatically and elect a leader automatically.  consul-alerts can run on any host with a consul agent running.

**Comment by akmalabbasov** [comment]
@fusiondog thank you. Currently I'm running consul-alerts in each machine where I have consul agent, which is more than 60. 
So I'm supposing that it's **better** to run consul alerts only on the consul server nodes, because
 - less communication overhead
 - consul-alerts depends on consul server, so even if it's deployed in all nodes, it won't work if consul server nodes failed.
Is it correct assumptions?
Thank you.

**Comment by fusiondog** [comment]
That all makes sense to me and seems to be the best way to distribute them.

**Comment by darkcrux** [comment]
Thanks @fusiondog. @akmalabbasov yeah, your assumption is correct, consul-alerts won't work when the server nodes are down so it's the best way to distribute them.
