### ISSUE TITLE
Crashes on notification!

### ISSUE THREAD

**Issue by ariscn** [AcalephStorage/consul-alerts#96]
Just set up consul-alerts, and it crashed right off the bat:

    INFO[0074] Notifications logged.
    DEBU[0074] struct = &{ClusterName:test cluster Url:https://hooks.slack.com/services/<redacted> Channel:#alerts2 Username:healthbot IconUrl: IconEmoji: Text:test cluster is HEALTHY.

    Fail: 0, Warn: 0, Pass: 1

    server:test:foo is passing.
     Attachments:[] Detailed:false NotifName:slack}, json = {"channel":"#alerts2","username":"healthbot","icon_url":"","icon_emoji":"","text":"test cluster is HEALTHY.\n\nFail: 0, Warn: 0, Pass: 1\n\nserver:test:foo is passing.\n","NotifName":"slack"}
    INFO[0074] Slack notification sent.
    panic: assignment to entry in nil map

    goroutine 12 [running]:
    github.com/AcalephStorage/consul-alerts/consul.(*ConsulAlertClient).CustomNotifiers(0xc820192050, 0x0)
        /home/ubuntu/go/src/github.com/AcalephStorage/consul-alerts/consul/client.go:338 +0x1c2
    main.(*NotifEngine).sendCustom(0xc8204f0ae0, 0xc82038c9a0, 0x1, 0x1)
        /home/ubuntu/go/src/github.com/AcalephStorage/consul-alerts/send-notifs.go:65 +0x59
    main.(*NotifEngine).start(0xc8204f0ae0)
        /home/ubuntu/go/src/github.com/AcalephStorage/consul-alerts/send-notifs.go:32 +0x12b
    created by main.startNotifEngine
        /home/ubuntu/go/src/github.com/AcalephStorage/consul-alerts/send-notifs.go:102 +0xcc

    goroutine 1 [chan receive, 1 minutes]:
    main.daemonMode(0xc82017c1b0)
        /home/ubuntu/go/src/github.com/AcalephStorage/consul-alerts/consul-alerts.go:126 +0x178c
    main.main()
        /home/ubuntu/go/src/github.com/AcalephStorage/consul-alerts/consul-alerts.go:54 +0x133

    goroutine 17 [syscall, 1 minutes, locked to thread]:
    runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

    goroutine 5 [syscall, 1 minutes]:
    os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
    created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

    goroutine 20 [IO wait, 1 minutes]:
    net.runtime_pollWait(0x7f9f013b88f8, 0x72, 0xc8200100e0)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
    net.(*pollDesc).Wait(0xc8201ac290, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
    net.(*pollDesc).WaitRead(0xc8201ac290, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
    net.(*netFD).Read(0xc8201ac230, 0xc8201bc000, 0x1000, 0x1000, 0x0, 0x7f9f013b3028, 0xc8200100e0)
        /usr/local/go/src/net/fd_unix.go:232 +0x23a
    net.(*conn).Read(0xc8201b8010, 0xc8201bc000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xe4
    net/http.noteEOFReader.Read(0x7f9f021f3200, 0xc8201b8010, 0xc8201ba058, 0xc8201bc000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1370 +0x67
    net/http.(*noteEOFReader).Read(0xc820194200, 0xc8201bc000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        <autogenerated>:126 +0xd0
    bufio.(*Reader).fill(0xc8201a8600)
        /usr/local/go/src/bufio/bufio.go:97 +0x1e9
    bufio.(*Reader).Peek(0xc8201a8600, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0xcc
    net/http.(*persistConn).readLoop(0xc8201ba000)
        /usr/local/go/src/net/http/transport.go:876 +0xf7
    created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:685 +0xc78

    goroutine 21 [select, 1 minutes]:
    net/http.(*persistConn).writeLoop(0xc8201ba000)
        /usr/local/go/src/net/http/transport.go:1009 +0x40c
    created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:686 +0xc9d

    goroutine 11 [chan receive, 1 minutes]:
    main.(*LeaderElection).start(0xc8204d1f60)
        /home/ubuntu/go/src/github.com/AcalephStorage/consul-alerts/leader-election.go:30 +0x289
    created by main.startLeaderElection
        /home/ubuntu/go/src/github.com/AcalephStorage/consul-alerts/leader-election.go:66 +0x19c

    goroutine 13 [select, 1 minutes]:
    main.(*EventProcessor).start(0xc8204d1fa0)
        /home/ubuntu/go/src/github.com/AcalephStorage/consul-alerts/event-handler.go:24 +0x156
    created by main.startEventProcessor
        /home/ubuntu/go/src/github.com/AcalephStorage/consul-alerts/event-handler.go:95 +0xd7

    goroutine 14 [select]:
    main.(*CheckProcessor).start(0xc8204c5860)
        /home/ubuntu/go/src/github.com/AcalephStorage/consul-alerts/check-handler.go:25 +0x156
    created by main.startCheckProcessor
        /home/ubuntu/go/src/github.com/AcalephStorage/consul-alerts/check-handler.go:152 +0x111

    goroutine 15 [select, 1 minutes]:
    main.(*CheckProcessor).reminderStart(0xc8204c5860)
        /home/ubuntu/go/src/github.com/AcalephStorage/consul-alerts/check-handler.go:42 +0x121
    created by main.startCheckProcessor
        /home/ubuntu/go/src/github.com/AcalephStorage/consul-alerts/check-handler.go:153 +0x133

    goroutine 16 [IO wait]:
    net.runtime_pollWait(0x7f9f013b8838, 0x72, 0xc8200100e0)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
    net.(*pollDesc).Wait(0xc820504300, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
    net.(*pollDesc).WaitRead(0xc820504300, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
    net.(*netFD).accept(0xc8205042a0, 0x0, 0x7f9f021f3000, 0xc820415da0)
        /usr/local/go/src/net/fd_unix.go:408 +0x27c
    net.(*TCPListener).AcceptTCP(0xc82002f9d8, 0x45c750, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
    net/http.tcpKeepAliveListener.Accept(0xc82002f9d8, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2135 +0x41
    net/http.(*Server).Serve(0xc8204f2d20, 0x7f9f013bcc10, 0xc82002f9d8, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1887 +0xb3
    net/http.(*Server).ListenAndServe(0xc8204f2d20, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1877 +0x136
    net/http.ListenAndServe(0x7fffc04868aa, 0xe, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1967 +0x8f
    main.startAPI(0x7fffc04868aa, 0xe)
        /home/ubuntu/go/src/github.com/AcalephStorage/consul-alerts/consul-alerts.go:131 +0x49
    created by main.daemonMode
        /home/ubuntu/go/src/github.com/AcalephStorage/consul-alerts/consul-alerts.go:113 +0x1358

    goroutine 50 [syscall, 1 minutes]:
    syscall.Syscall6(0x3d, 0x56b7, 0xc82003bb24, 0x0, 0xc8204ca000, 0x0, 0x0, 0x45a5b0, 0x7f9f023a3000, 0xa)
        /usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
    syscall.wait4(0x56b7, 0xc82003bb24, 0x0, 0xc8204ca000, 0x90, 0x0, 0x0)
        /usr/local/go/src/syscall/zsyscall_linux_amd64.go:172 +0x72
    syscall.Wait4(0x56b7, 0xc82003bb6c, 0x0, 0xc8204ca000, 0xc82002e018, 0x0, 0x0)
        /usr/local/go/src/syscall/syscall_linux.go:256 +0x55
    os.(*Process).wait(0xc8204e0000, 0x14, 0x0, 0x0)
        /usr/local/go/src/os/exec_unix.go:22 +0x105
    os.(*Process).Wait(0xc8204e0000, 0x0, 0x0, 0x0)
        /usr/local/go/src/os/doc.go:45 +0x2d
    os/exec.(*Cmd).Wait(0xc8203223c0, 0x0, 0x0)
        /usr/local/go/src/os/exec/exec.go:380 +0x211
    os/exec.(*Cmd).Run(0xc8203223c0, 0x0, 0x0)
        /usr/local/go/src/os/exec/exec.go:258 +0x64
    main.runWatcher(0xc8200188fe, 0xe, 0x7fffc0486896, 0x6, 0x7fffc04868aa, 0xe, 0x7fffc04868d4, 0x5, 0x9c2558, 0x6)
        /home/ubuntu/go/src/github.com/AcalephStorage/consul-alerts/watchers.go:26 +0x2be
    created by main.daemonMode
        /home/ubuntu/go/src/github.com/AcalephStorage/consul-alerts/consul-alerts.go:118 +0x14de

    goroutine 51 [select, 1 minutes, locked to thread]:
    runtime.gopark(0xaba350, 0xc82052af28, 0x9c6278, 0x6, 0x18, 0x2)
        /usr/local/go/src/runtime/proc.go:185 +0x163
    runtime.selectgoImpl(0xc82052af28, 0x0, 0x18)
        /usr/local/go/src/runtime/select.go:392 +0xa64
    runtime.selectgo(0xc82052af28)
        /usr/local/go/src/runtime/select.go:212 +0x12
    runtime.ensureSigM.func1()
        /usr/local/go/src/runtime/signal1_unix.go:227 +0x353
    runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

    goroutine 35 [select]:
    github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/hashicorp/consul/api.(*Session).RenewPeriodic(0xc8201de008, 0x9be878, 0x3, 0xc820013020, 0x24, 0x0, 0xc8204e2000, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/hashicorp/consul/api/session.go:143 +0x37d
    created by github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/hashicorp/consul/api.(*Lock).Lock
        /home/ubuntu/go/src/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/hashicorp/consul/api/lock.go:134 +0x3ef

    goroutine 52 [select, 1 minutes]:
    net/http.(*persistConn).roundTrip(0xc8201ba000, 0xc820192560, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1164 +0xb0d
    net/http.(*Transport).RoundTrip(0xc820080120, 0xc8204de2a0, 0xaf, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:235 +0x530
    net/http.send(0xc8204de2a0, 0x7f9f013b74d8, 0xc820080120, 0xc8203f0420, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:220 +0x52c
    net/http.(*Client).send(0xc80200, 0xc8204de2a0, 0x60, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:143 +0x15a
    net/http.(*Client).doFollowingRedirects(0xc80200, 0xc8204de2a0, 0xab9f28, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:380 +0xbc0
    net/http.(*Client).Do(0xc80200, 0xc8204de2a0, 0xc80380, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:175 +0x9c
    github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/hashicorp/consul/api.(*Client).doRequest(0xc8204f2960, 0xc8204920f0, 0xc82004bd98, 0xc8203d84e0, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/hashicorp/consul/api/api.go:335 +0xd5
    github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/hashicorp/consul/api.(*KV).getInternal(0xc82004bf18, 0xa21e70, 0x14, 0x0, 0xc82004bf40, 0xc8204c2240, 0xc8203d83c0, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/hashicorp/consul/api/kv.go:104 +0x28c
    github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/hashicorp/consul/api.(*KV).Get(0xc82004bf18, 0xa21e70, 0x14, 0xc82004bf40, 0x0, 0x0, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/hashicorp/consul/api/kv.go:38 +0x8a
    github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/hashicorp/consul/api.(*Lock).monitorLock(0xc82047d980, 0xc820013020, 0x24, 0xc8203f01e0)
        /home/ubuntu/go/src/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/hashicorp/consul/api/lock.go:330 +0x117
    created by github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/hashicorp/consul/api.(*Lock).Lock
        /home/ubuntu/go/src/github.com/AcalephStorage/consul-alerts/Godeps/_workspace/src/github.com/hashicorp/consul/api/lock.go:209 +0x802

    goroutine 42 [IO wait]:
    net.runtime_pollWait(0x7f9f013b8778, 0x72, 0xc8200100e0)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
    net.(*pollDesc).Wait(0xc8205b9aa0, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
    net.(*pollDesc).WaitRead(0xc8205b9aa0, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
    net.(*netFD).Read(0xc8205b9a40, 0xc8201e5000, 0x1000, 0x1000, 0x0, 0x7f9f013b3028, 0xc8200100e0)
        /usr/local/go/src/net/fd_unix.go:232 +0x23a
    net.(*conn).Read(0xc8201de628, 0xc8201e5000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xe4
    net/http.noteEOFReader.Read(0x7f9f021f3200, 0xc8201de628, 0xc8200e3b28, 0xc8201e5000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1370 +0x67
    net/http.(*noteEOFReader).Read(0xc8205b3c00, 0xc8201e5000, 0x1000, 0x1000, 0xc8201164d0, 0x0, 0x0)
        <autogenerated>:126 +0xd0
    bufio.(*Reader).fill(0xc8205bf080)
        /usr/local/go/src/bufio/bufio.go:97 +0x1e9
    bufio.(*Reader).Peek(0xc8205bf080, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0xcc
    net/http.(*persistConn).readLoop(0xc8200e3ad0)
        /usr/local/go/src/net/http/transport.go:876 +0xf7
    created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:685 +0xc78

    goroutine 38 [IO wait]:
    net.runtime_pollWait(0x7f9f013b86b8, 0x72, 0xc8200100e0)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
    net.(*pollDesc).Wait(0xc8200624c0, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
    net.(*pollDesc).WaitRead(0xc8200624c0, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
    net.(*netFD).Read(0xc820062460, 0xc8203d6000, 0x1000, 0x1000, 0x0, 0x7f9f013b3028, 0xc8200100e0)
        /usr/local/go/src/net/fd_unix.go:232 +0x23a
    net.(*conn).Read(0xc8201de030, 0xc8203d6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xe4
    net/http.noteEOFReader.Read(0x7f9f021f3200, 0xc8201de030, 0xc8200e21b8, 0xc8203d6000, 0x1000, 0x1000, 0x4aa1e9, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1370 +0x67
    net/http.(*noteEOFReader).Read(0xc82000e9e0, 0xc8203d6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        <autogenerated>:126 +0xd0
    bufio.(*Reader).fill(0xc8204e2540)
        /usr/local/go/src/bufio/bufio.go:97 +0x1e9
    bufio.(*Reader).Peek(0xc8204e2540, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0xcc
    net/http.(*persistConn).readLoop(0xc8200e2160)
        /usr/local/go/src/net/http/transport.go:876 +0xf7
    created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:685 +0xc78

    goroutine 39 [select]:
    net/http.(*persistConn).writeLoop(0xc8200e2160)
        /usr/local/go/src/net/http/transport.go:1009 +0x40c
    created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:686 +0xc9d

    goroutine 43 [select]:
    net/http.(*persistConn).writeLoop(0xc8200e3ad0)
        /usr/local/go/src/net/http/transport.go:1009 +0x40c
    created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:686 +0xc9d

**Comment by ariscn** [comment]
It looks like an empty `consul-alerts/config/notifiers/custom/` triggers this.

**Comment by fusiondog** [comment]
I submitted a pull request for this https://github.com/AcalephStorage/consul-alerts/pull/99

**Comment by fusiondog** [comment]
The fix has been merged in.  Closing.
