### ISSUE TITLE
Profile and reminder docs unclear

### ISSUE THREAD

**Issue by ariscn** [AcalephStorage/consul-alerts#97]
> Profiles may be configured as keys in consul-alerts/config/notif-profiles/. The key name is the name of the profile and the value should be a JSON object with an "Interval" key set to an int in minutes and a key "NotifList" that should be an object of profile names as keys and true for the value.

This is pretty confusing. How exactly does NotifList work?

> Reminders are processed every five minutes. Interval values should be a multiple of five. If the Interval value is 0 or not set then reminders will not be set.

Okay, but what exactly is a reminder and how is it different from a notification?

**Comment by fusiondog** [comment]
Doc updates merged in.  Closing.
